packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@firebase/util'
  - '@hatchet-dev/typescript-sdk'
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@temporalio/core-bridge'
  - cpu-features
  - esbuild
  - lefthook
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
